# Generated by Django 5.2.12 on 2026-03-28 23:17

import apps.usuario.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('datos_personales', '0001_initial'),
        ('estado_socio', '0001_initial'),
        ('tipo_socio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('is_editable', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('fch_ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('dni', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('cuil', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(19999999999), django.core.validators.MaxValueValidator(99999999999)])),
                ('fch_nacimiento', models.DateField()),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_gral_flia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('es_admin_local', models.BooleanField(default=False)),
                ('operador_sistema', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, storage=apps.usuario.models.OverwriteStorage(), upload_to=apps.usuario.models.ruta_foto_usuario)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='datos_jerarquia', to='datos_personales.jerarquia')),
                ('id_std_socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='datos_estado', to='estado_socio.estadosocio')),
                ('id_tipo_socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='datos_tipo', to='tipo_socio.tiposocio')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalUsuario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fch_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fch_ultimo_acceso', models.DateTimeField(blank=True, editable=False)),
                ('dni', models.PositiveBigIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('cuil', models.PositiveBigIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(19999999999), django.core.validators.MaxValueValidator(99999999999)])),
                ('fch_nacimiento', models.DateField()),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_gral_flia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('es_admin_local', models.BooleanField(default=False)),
                ('operador_sistema', models.BooleanField(default=False)),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_jerarquia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datos_personales.jerarquia')),
                ('id_std_socio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estado_socio.estadosocio')),
                ('id_tipo_socio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tipo_socio.tiposocio')),
            ],
            options={
                'verbose_name': 'historical usuario',
                'verbose_name_plural': 'historical usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentoUsuario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('archivo', models.TextField(max_length=100, validators=[apps.usuario.models.validar_peso_pdf])),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_subida', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.tipodocumento')),
            ],
            options={
                'verbose_name': 'historical documento usuario',
                'verbose_name_plural': 'historical documento usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentoTipoSocio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_socio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tipo_socio.tiposocio')),
                ('tipo_documento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.tipodocumento')),
            ],
            options={
                'verbose_name': 'historical documento tipo socio',
                'verbose_name_plural': 'historical documento tipo socios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.usuario.models.ruta_documento_usuario, validators=[apps.usuario.models.validar_peso_pdf])),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_subida', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Pendiente',
                'verbose_name_plural': 'Usuarios Pendientes',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTipoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('tipo_socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentos_requeridos', to='tipo_socio.tiposocio')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.tipodocumento')),
            ],
            options={
                'unique_together': {('tipo_socio', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoUsuarioPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.usuario.models.ruta_documento_usuario_pendiente, validators=[apps.usuario.models.validar_peso_pdf])),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_subida', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.tipodocumento')),
                ('usuario_pendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuario.usuariopendiente')),
            ],
            options={
                'unique_together': {('usuario_pendiente', 'tipo_documento')},
            },
        ),
    ]
