# Generated by Django 5.2.12 on 2026-03-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_personales', '0002_initial'),
        ('estado_socio', '0002_initial'),
        ('tipo_socio', '0002_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_jerarquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='datos_jerarquia', to='datos_personales.jerarquia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_std_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='datos_estado', to='estado_socio.estadosocio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='datos_tipo', to='tipo_socio.tiposocio'),
        ),
    ]
