# Generated by Django 5.2.12 on 2026-04-02 04:21

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_socio', '0003_relacion_cant_max_flia'),
        ('usuario', '0003_alter_usuario_id_jerarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='cuil',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(19999999999), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cuil',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(19999999999), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentoRelacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('relacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tipo_socio.relacion')),
                ('tipo_documento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario.tipodocumento')),
            ],
            options={
                'verbose_name': 'historical documento relacion',
                'verbose_name_plural': 'historical documento relacions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentoRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('relacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentos_requeridos_relacion', to='tipo_socio.relacion')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.tipodocumento')),
            ],
            options={
                'unique_together': {('relacion', 'tipo_documento')},
            },
        ),
    ]
