# Generated by Django 5.2.14 on 2026-05-09 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_recalcular_ciclo_vida_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='titulo',
            field=models.FileField(default='', upload_to='psicologos/titulos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Titulo'),
        ),
    ]
