# Generated by Django 5.2.14 on 2026-05-09 06:40

import apps.usuario.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0006_actualizar_ciclos_vida'),
        ('usuario', '0004_psicologo_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsicologoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('dni', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('cuil', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)])),
                ('fch_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('foto', models.FileField(blank=True, null=True, upload_to='personas/fotos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.usuario.models.validate_photo_size])),
                ('titulo', models.FileField(upload_to='psicologos/titulos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Titulo')),
                ('telefono', models.CharField(max_length=25)),
                ('domicilio', models.CharField(max_length=200)),
                ('password_hash', models.CharField(max_length=128)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=12)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('fch_actualizacion', models.DateTimeField(auto_now=True)),
                ('fch_resolucion', models.DateTimeField(blank=True, null=True)),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.localidad', verbose_name='Localidad')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.pais', verbose_name='Pais')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.provincia', verbose_name='Provincia')),
                ('id_rama', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='psicologos_pendientes', to='parametro.rama', verbose_name='Rama')),
                ('id_sexo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.sexo', verbose_name='Sexo')),
                ('id_std_civil', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.tipocivil', verbose_name='Estado civil')),
                ('id_zona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.zona', verbose_name='Zona')),
                ('psicologo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='usuario.psicologo')),
            ],
            options={
                'verbose_name': 'Psicologo pendiente',
                'verbose_name_plural': 'Psicologos pendientes',
                'ordering': ('-fch_creacion',),
            },
        ),
    ]
