# Generated by Django 5.2.14 on 2026-05-09 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0006_actualizar_ciclos_vida'),
        ('usuario', '0005_psicologopendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsicologoMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='psicologo_metodo_pago', to='parametro.estado', verbose_name='Estado')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.metodopago', verbose_name='Método de pago')),
                ('id_psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='usuario.psicologo', verbose_name='Psicologo')),
            ],
            options={
                'verbose_name': 'Método de pago del psicólogo',
                'verbose_name_plural': 'Métodos de pago de los psicólogos',
            },
        ),
        migrations.CreateModel(
            name='PsicologoOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('telefono', models.CharField(max_length=25, verbose_name='Teléfono')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='psicologo_oficina', to='parametro.estado', verbose_name='Estado')),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.localidad', verbose_name='Localidad')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.pais', verbose_name='Pais')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.provincia', verbose_name='Provincia')),
                ('id_psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='usuario.psicologo', verbose_name='Psicologo')),
                ('id_zona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Oficina del psicólogo',
                'verbose_name_plural': 'Oficinas de los psicólogos',
            },
        ),
    ]
