# Generated by Django 5.2.14 on 2026-05-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0006_actualizar_ciclos_vida'),
        ('usuario', '0006_psicologometodopago_psicologooficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsicologoIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='psicologo_idioma', to='parametro.estado', verbose_name='Estado')),
                ('id_idioma', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.idioma', verbose_name='Idioma')),
                ('id_psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='usuario.psicologo', verbose_name='Psicologo')),
            ],
            options={
                'verbose_name': 'Idioma del psicólogo',
                'verbose_name_plural': 'Idiomas de los psicólogos',
            },
        ),
    ]
