# Generated by Django 5.2.14 on 2026-05-14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_psicologo_ramas(apps, schema_editor):
    Psicologo = apps.get_model("usuario", "Psicologo")
    PsicologoRama = apps.get_model("usuario", "PsicologoRama")

    relaciones = []
    for psicologo in Psicologo.objects.exclude(id_rama=None).iterator():
        relaciones.append(
            PsicologoRama(
                id_psicologo_id=psicologo.pk,
                id_rama_id=psicologo.id_rama_id,
                valor_sesion=0,
                id_estado_id=psicologo.id_estado_id,
            )
        )

    if relaciones:
        PsicologoRama.objects.bulk_create(relaciones)


def backwards_restore_psicologo_rama(apps, schema_editor):
    Psicologo = apps.get_model("usuario", "Psicologo")
    PsicologoRama = apps.get_model("usuario", "PsicologoRama")

    for psicologo in Psicologo.objects.all().iterator():
        rama_rel = (
            PsicologoRama.objects.filter(id_psicologo_id=psicologo.pk)
            .order_by("id_psico_rama")
            .first()
        )
        if rama_rel is None:
            continue
        psicologo.id_rama_id = rama_rel.id_rama_id
        psicologo.save(update_fields=["id_rama"])


class Migration(migrations.Migration):

    dependencies = [
        ("parametro", "0006_actualizar_ciclos_vida"),
        ("usuario", "0007_psicologoidioma"),
    ]

    operations = [
        migrations.AddField(
            model_name="psicologopendiente",
            name="valor_sesion",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor de sesion",
            ),
        ),
        migrations.CreateModel(
            name="PsicologoRama",
            fields=[
                (
                    "id_psico_rama",
                    models.AutoField(
                        db_column="id_psico_rama",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "valor_sesion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor de sesion",
                    ),
                ),
                (
                    "id_estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="psicologo_ramas",
                        to="parametro.estado",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "id_psicologo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ramas",
                        to="usuario.psicologo",
                        verbose_name="Psicologo",
                    ),
                ),
                (
                    "id_rama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="psicologo_ramas",
                        to="parametro.rama",
                        verbose_name="Rama",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rama del psicologo",
                "verbose_name_plural": "Ramas de los psicologos",
            },
        ),
        migrations.RunPython(
            forwards_copy_psicologo_ramas,
            backwards_restore_psicologo_rama,
        ),
        migrations.RemoveField(
            model_name="psicologo",
            name="id_rama",
        ),
        migrations.AddConstraint(
            model_name="psicologorama",
            constraint=models.UniqueConstraint(
                fields=("id_psicologo", "id_rama"),
                name="uniq_psicologo_rama",
            ),
        ),
    ]
