# Generated by Django 5.2.14 on 2026-05-14

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_psicologo_pendiente_ramas(apps, schema_editor):
    PsicologoPendiente = apps.get_model("usuario", "PsicologoPendiente")
    PsicologoPendienteRama = apps.get_model("usuario", "PsicologoPendienteRama")

    relaciones = []
    for solicitud in PsicologoPendiente.objects.exclude(id_rama=None).iterator():
        relaciones.append(
            PsicologoPendienteRama(
                id_psicologo_pendiente_id=solicitud.pk,
                id_rama_id=solicitud.id_rama_id,
            )
        )

    if relaciones:
        PsicologoPendienteRama.objects.bulk_create(relaciones)


def backwards_restore_psicologo_pendiente_rama(apps, schema_editor):
    PsicologoPendiente = apps.get_model("usuario", "PsicologoPendiente")
    PsicologoPendienteRama = apps.get_model("usuario", "PsicologoPendienteRama")

    for solicitud in PsicologoPendiente.objects.all().iterator():
        rama_rel = (
            PsicologoPendienteRama.objects.filter(id_psicologo_pendiente_id=solicitud.pk)
            .order_by("id_psico_pend_rama")
            .first()
        )
        if rama_rel is None:
            continue

        solicitud.id_rama_id = rama_rel.id_rama_id
        solicitud.valor_sesion = 0
        solicitud.save(update_fields=["id_rama", "valor_sesion"])


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0008_remove_psicologo_id_rama_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PsicologoPendienteRama",
            fields=[
                (
                    "id_psico_pend_rama",
                    models.AutoField(
                        db_column="id_psico_pend_rama",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_psicologo_pendiente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ramas_pendientes",
                        to="usuario.psicologopendiente",
                        verbose_name="Solicitud de psicologo",
                    ),
                ),
                (
                    "id_rama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="psicologo_pendiente_ramas",
                        to="parametro.rama",
                        verbose_name="Rama",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rama seleccionada en solicitud",
                "verbose_name_plural": "Ramas seleccionadas en solicitudes",
            },
        ),
        migrations.RunPython(
            forwards_copy_psicologo_pendiente_ramas,
            backwards_restore_psicologo_pendiente_rama,
        ),
        migrations.RemoveField(
            model_name="psicologopendiente",
            name="id_rama",
        ),
        migrations.RemoveField(
            model_name="psicologopendiente",
            name="valor_sesion",
        ),
        migrations.AddConstraint(
            model_name="psicologopendienterama",
            constraint=models.UniqueConstraint(
                fields=("id_psicologo_pendiente", "id_rama"),
                name="uniq_psicologo_pendiente_rama",
            ),
        ),
    ]
