# Generated by Django 5.2.14 on 2026-05-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_psicologopendienterama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologopendiente',
            name='sobre_mi',
            field=models.TextField(blank=True, default='', help_text='Descripción breve del enfoque, experiencia y forma de trabajo del psicólogo.', verbose_name='Sobre mí'),
        ),
    ]
