# Generated by Django 5.2.14 on 2026-05-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_psicologopendiente_sobre_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sobre_mi',
            field=models.TextField(blank=True, default='', help_text='Descripción sobre la persona.', verbose_name='Sobre mí'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='sobre_mi',
            field=models.TextField(blank=True, default='', help_text='Descripción sobre la persona.', verbose_name='Sobre mí'),
        ),
    ]
