# Generated by Django 5.2.14 on 2026-05-15 11:45

import apps.usuario.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametro", "0006_actualizar_ciclos_vida"),
        ("usuario", "0011_paciente_sobre_mi_psicologo_sobre_mi"),
    ]

    operations = [
        migrations.CreateModel(
            name="PacientePendiente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombres", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50)),
                (
                    "dni",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000000),
                            django.core.validators.MaxValueValidator(99999999),
                        ]
                    ),
                ),
                (
                    "cuil",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10000000000),
                            django.core.validators.MaxValueValidator(99999999999),
                        ],
                    ),
                ),
                ("fch_nacimiento", models.DateField(verbose_name="Fecha de nacimiento")),
                (
                    "foto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="personas/fotos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png", "webp"]),
                            apps.usuario.models.validate_photo_size,
                        ],
                    ),
                ),
                (
                    "sobre_mi",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción sobre la persona.",
                        verbose_name="Sobre mí",
                    ),
                ),
                ("telefono", models.CharField(max_length=25)),
                ("domicilio", models.CharField(max_length=200)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "estado",
                    models.CharField(
                        choices=[("PENDIENTE", "Pendiente"), ("APROBADO", "Aprobado"), ("RECHAZADO", "Rechazado")],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                ("fch_creacion", models.DateTimeField(auto_now_add=True)),
                ("fch_actualizacion", models.DateTimeField(auto_now=True)),
                ("fch_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "id_ciclo_vida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pacientes_pendientes",
                        to="parametro.ciclovida",
                        verbose_name="Ciclo de vida",
                    ),
                ),
                (
                    "id_grado_estudio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pacientes_pendientes",
                        to="parametro.gradoestudio",
                        verbose_name="Grado de estudio",
                    ),
                ),
                (
                    "id_localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="parametro.localidad",
                        verbose_name="Localidad",
                    ),
                ),
                (
                    "id_ocupacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pacientes_pendientes",
                        to="parametro.ocupacion",
                        verbose_name="Ocupacion",
                    ),
                ),
                (
                    "id_pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="parametro.pais",
                        verbose_name="Pais",
                    ),
                ),
                (
                    "id_provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="parametro.provincia",
                        verbose_name="Provincia",
                    ),
                ),
                (
                    "id_sexo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="parametro.sexo",
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "id_std_civil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="parametro.tipocivil",
                        verbose_name="Estado civil",
                    ),
                ),
                (
                    "id_zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="parametro.zona",
                        verbose_name="Zona",
                    ),
                ),
                (
                    "paciente",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitud_origen",
                        to="usuario.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente pendiente",
                "verbose_name_plural": "Pacientes pendientes",
                "ordering": ("-fch_creacion",),
            },
        ),
    ]
