# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_socio', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('telefono', models.CharField(max_length=25)),
                ('domicilio', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Dato Personal',
                'verbose_name_plural': 'Datos Personales',
                'ordering': ['-nro_socio'],
            },
        ),
        migrations.CreateModel(
            name='DatosPersonalesPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Datos Personales Pendiente',
                'verbose_name_plural': 'Datos Personales Pendientes',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_std_civil', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_std_civil', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'ESTADO CIVIL',
                'verbose_name_plural': 'ESTADOS CIVILES',
                'ordering': ['dsc_std_civil'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDatosPersonales',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nro_socio', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('telefono', models.CharField(max_length=25)),
                ('domicilio', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Dato Personal',
                'verbose_name_plural': 'historical Datos Personales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEstadoCivil',
            fields=[
                ('id_std_civil', models.IntegerField(blank=True, db_index=True)),
                ('dsc_std_civil', models.CharField(db_index=True, max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical ESTADO CIVIL',
                'verbose_name_plural': 'historical ESTADOS CIVILES',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJerarquia',
            fields=[
                ('id_jerarquia', models.IntegerField(blank=True, db_index=True)),
                ('dsc_jerarquia', models.CharField(db_index=True, max_length=20)),
                ('nivel', models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical JERARQUIA',
                'verbose_name_plural': 'historical JERARQUIAS',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLocalidad',
            fields=[
                ('id_localidad', models.IntegerField(blank=True, db_index=True)),
                ('dsc_localidad', models.CharField(db_index=True, max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical LOCALIDAD',
                'verbose_name_plural': 'historical LOCALIDADES',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPais',
            fields=[
                ('id_pais', models.IntegerField(blank=True, db_index=True)),
                ('dsc_pais', models.CharField(db_index=True, max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical PAIS',
                'verbose_name_plural': 'historical PAISES',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProvincia',
            fields=[
                ('id_provincia', models.IntegerField(blank=True, db_index=True)),
                ('dsc_provincia', models.CharField(db_index=True, max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical PROVINCIA',
                'verbose_name_plural': 'historical PROVINCIAS',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalZona',
            fields=[
                ('id_zona', models.IntegerField(blank=True, db_index=True)),
                ('dsc_zona', models.CharField(db_index=True, max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical ZONA',
                'verbose_name_plural': 'historical ZONAS',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id_jerarquia', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_jerarquia', models.CharField(max_length=20, unique=True)),
                ('nivel', models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'JERARQUIA',
                'verbose_name_plural': 'JERARQUIAS',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_localidad', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'LOCALIDAD',
                'verbose_name_plural': 'LOCALIDADES',
                'ordering': ['dsc_localidad'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_pais', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'PAIS',
                'verbose_name_plural': 'PAISES',
                'ordering': ['dsc_pais'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_provincia', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'PROVINCIA',
                'verbose_name_plural': 'PROVINCIAS',
                'ordering': ['dsc_provincia'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_zona', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'ZONA',
                'verbose_name_plural': 'ZONAS',
                'ordering': ['dsc_zona'],
            },
        ),
        migrations.CreateModel(
            name='DatosPersonalesAdmin',
            fields=[
                ('datospersonales_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datos_personales.datospersonales')),
            ],
            bases=('datos_personales.datospersonales',),
        ),
    ]
