# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_personales', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuario_datos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datospersonalespendiente',
            name='usuario_pendiente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_pendientes', to='usuario.usuariopendiente'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='id_std_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datos_personales.estadocivil'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonales',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldatospersonales',
            name='id_std_civil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datos_personales.estadocivil'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonales',
            name='username',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalestadocivil',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljerarquia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocalidad',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpais',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprovincia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalzona',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldatospersonales',
            name='id_localidad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datos_personales.localidad'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datos_personales.localidad'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonales',
            name='id_pais',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datos_personales.pais'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datos_personales.pais'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonales',
            name='id_provincia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datos_personales.provincia'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datos_personales.provincia'),
        ),
        migrations.AddField(
            model_name='historicaldatospersonales',
            name='id_zona',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datos_personales.zona'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='id_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datos_personales.zona'),
        ),
    ]
