# Generated by Django 5.2.12 on 2026-03-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_personales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljerarquia',
            name='dsc_jerarquia',
            field=models.CharField(db_index=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='jerarquia',
            name='dsc_jerarquia',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
