# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('alta_socio', 'Alta de socio'), ('cuota_generada', 'Cuota generada'), ('pago_confirmado', 'Pago confirmado')], max_length=50)),
                ('provider', models.CharField(choices=[('gmail_cuotas', 'Gmail Cuotas'), ('gmail_pagos', 'Gmail Pagos'), ('gmail_sistema', 'Gmail Sistema')], max_length=50)),
                ('asunto', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=100)),
                ('contexto', models.JSONField(default=dict)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='emails_adjuntos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('programado', 'Programado'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('prioridad', models.IntegerField(default=5)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=0)),
                ('max_intentos', models.IntegerField(default=3)),
                ('error', models.TextField(blank=True, null=True)),
                ('clave_unica', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha_programada', 'prioridad', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('nivel', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='ERROR', max_length=20)),
                ('mensaje', models.TextField(verbose_name='Mensaje humano')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Traceback técnico')),
                ('ruta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivo y función')),
                ('metodo_http', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('modulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='App o módulo origen')),
            ],
            options={
                'verbose_name': 'Log del Sistema',
                'verbose_name_plural': 'Logs del Sistema',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
