# Generated by Django 5.2.12 on 2026-03-28 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colaemail',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logsistema',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario logueado'),
        ),
        migrations.AddField(
            model_name='visita',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario vinculado'),
        ),
        migrations.AddIndex(
            model_name='colaemail',
            index=models.Index(fields=['estado', 'provider'], name='core_colaem_estado_9ecceb_idx'),
        ),
        migrations.AddIndex(
            model_name='colaemail',
            index=models.Index(fields=['fecha_programada'], name='core_colaem_fecha_p_6a2374_idx'),
        ),
        migrations.AddConstraint(
            model_name='colaemail',
            constraint=models.UniqueConstraint(condition=models.Q(('clave_unica', None), _negated=True), fields=('clave_unica',), name='unique_clave_unica_not_null'),
        ),
    ]
