# Generated by Django 5.2.14 on 2026-05-05 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_estado', models.AutoField(db_column='id_estado', primary_key=True, serialize=False)),
                ('dsc_estado', models.CharField(db_column='dsc_estado', max_length=150)),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'db_table': 'estado',
                'ordering': ('dsc_estado', 'id_estado'),
            },
        ),
        migrations.CreateModel(
            name='GradoEstudio',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_grado_estudio', models.AutoField(db_column='id_grado_estudio', primary_key=True, serialize=False)),
                ('dsc_grado_estudio', models.CharField(db_column='dsc_grado_estudio', max_length=150)),
            ],
            options={
                'verbose_name': 'grado de estudio',
                'verbose_name_plural': 'grados de estudio',
                'db_table': 'grado_estudio',
                'ordering': ('dsc_grado_estudio', 'id_grado_estudio'),
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_idioma', models.AutoField(db_column='id_idioma', primary_key=True, serialize=False)),
                ('dsc_idioma', models.CharField(db_column='dsc_idioma', max_length=150)),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
                'db_table': 'idioma',
                'ordering': ('dsc_idioma', 'id_idioma'),
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_localidad', models.AutoField(db_column='id_localidad', primary_key=True, serialize=False)),
                ('dsc_localidad', models.CharField(db_column='dsc_localidad', max_length=150)),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
                'db_table': 'localidad',
                'ordering': ('dsc_localidad', 'id_localidad'),
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_metodo_pago', models.AutoField(db_column='id_metodo_pago', primary_key=True, serialize=False)),
                ('dsc_met_pago', models.CharField(db_column='dsc_met_pago', max_length=150)),
            ],
            options={
                'verbose_name': 'metodo de pago',
                'verbose_name_plural': 'metodos de pago',
                'db_table': 'metodo_pago',
                'ordering': ('dsc_met_pago', 'id_metodo_pago'),
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_ocupacion', models.AutoField(db_column='id_ocupacion', primary_key=True, serialize=False)),
                ('dsc_ocupacion', models.CharField(db_column='dsc_ocupacion', max_length=150)),
            ],
            options={
                'verbose_name': 'ocupacion',
                'verbose_name_plural': 'ocupaciones',
                'db_table': 'ocupacion',
                'ordering': ('dsc_ocupacion', 'id_ocupacion'),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_pais', models.AutoField(db_column='id_pais', primary_key=True, serialize=False)),
                ('dsc_pais', models.CharField(db_column='dsc_pais', max_length=150)),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
                'db_table': 'pais',
                'ordering': ('dsc_pais', 'id_pais'),
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_sexo', models.AutoField(db_column='id_sexo', primary_key=True, serialize=False)),
                ('dsc_tipo', models.CharField(db_column='dsc_tipo', max_length=150)),
            ],
            options={
                'verbose_name': 'sexo',
                'verbose_name_plural': 'sexos',
                'db_table': 'sexo',
                'ordering': ('dsc_tipo', 'id_sexo'),
            },
        ),
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_tipo_cita', models.AutoField(db_column='id_tipo_cita', primary_key=True, serialize=False)),
                ('dsc_t_cita', models.CharField(db_column='dsc_t_cita', max_length=150)),
            ],
            options={
                'verbose_name': 'tipo de cita',
                'verbose_name_plural': 'tipos de cita',
                'db_table': 'tipo_cita',
                'ordering': ('dsc_t_cita', 'id_tipo_cita'),
            },
        ),
        migrations.CreateModel(
            name='TipoCivil',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_estado_civil', models.AutoField(db_column='id_estado_civil', primary_key=True, serialize=False)),
                ('dsc_std_civil', models.CharField(db_column='dsc_std_civil', max_length=150)),
            ],
            options={
                'verbose_name': 'tipo civil',
                'verbose_name_plural': 'tipos civiles',
                'db_table': 'tipo_civil',
                'ordering': ('dsc_std_civil', 'id_estado_civil'),
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_zona', models.AutoField(db_column='id_zona', primary_key=True, serialize=False)),
                ('dsc_zona', models.CharField(db_column='dsc_zona', max_length=150)),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zonas',
                'db_table': 'zona',
                'ordering': ('dsc_zona', 'id_zona'),
            },
        ),
        migrations.CreateModel(
            name='PaisZona',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_pais_zona', models.AutoField(db_column='id_pais_zona', primary_key=True, serialize=False)),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.PROTECT, related_name='pais_zonas', to='parametro.pais')),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.PROTECT, related_name='zona_paises', to='parametro.zona')),
            ],
            options={
                'verbose_name': 'pais zona',
                'verbose_name_plural': 'pais zonas',
                'db_table': 'pais_zona',
                'ordering': ('id_pais', 'id_zona', 'id_pais_zona'),
                'constraints': [models.UniqueConstraint(fields=('id_pais', 'id_zona'), name='uq_pais_zona')],
            },
        ),
        migrations.CreateModel(
            name='ZonaLocalidad',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_zona_localidad', models.AutoField(db_column='id_zona_localidad', primary_key=True, serialize=False)),
                ('id_localidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.PROTECT, related_name='localidad_zonas', to='parametro.localidad')),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.PROTECT, related_name='zona_localidades', to='parametro.zona')),
            ],
            options={
                'verbose_name': 'zona localidad',
                'verbose_name_plural': 'zona localidades',
                'db_table': 'zona_localidad',
                'ordering': ('id_zona', 'id_localidad', 'id_zona_localidad'),
                'constraints': [models.UniqueConstraint(fields=('id_zona', 'id_localidad'), name='uq_zona_localidad')],
            },
        ),
    ]
