# Generated by Django 5.2.14 on 2026-05-05 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_provincia', models.AutoField(db_column='id_provincia', primary_key=True, serialize=False)),
                ('dsc_provincia', models.CharField(db_column='dsc_provincia', max_length=150)),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'db_table': 'provincia',
                'ordering': ('dsc_provincia', 'id_provincia'),
            },
        ),
        migrations.CreateModel(
            name='ProvinciaLocalidad',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_provincia_localidad', models.AutoField(db_column='id_provincia_localidad', primary_key=True, serialize=False)),
                ('id_localidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.PROTECT, related_name='localidad_provincias', to='parametro.localidad')),
                ('id_provincia', models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.PROTECT, related_name='provincia_localidades', to='parametro.provincia')),
            ],
            options={
                'verbose_name': 'provincia localidad',
                'verbose_name_plural': 'provincias localidades',
                'db_table': 'provincia_localidad',
                'ordering': ('id_provincia', 'id_localidad', 'id_provincia_localidad'),
                'constraints': [models.UniqueConstraint(fields=('id_provincia', 'id_localidad'), name='uq_provincia_localidad')],
            },
        ),
    ]
