# Generated by Django 5.2.14 on 2026-05-05 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0002_provincia_provincialocalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaisProvincia',
            fields=[
                ('flg_activo', models.BooleanField(db_column='flg_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_pais_provincia', models.AutoField(db_column='id_pais_provincia', primary_key=True, serialize=False)),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.PROTECT, related_name='pais_provincias', to='parametro.pais')),
                ('id_provincia', models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.PROTECT, related_name='provincia_paises', to='parametro.provincia')),
            ],
            options={
                'verbose_name': 'pais provincia',
                'verbose_name_plural': 'paises provincias',
                'db_table': 'pais_provincia',
                'ordering': ('id_pais', 'id_provincia', 'id_pais_provincia'),
            },
        ),
        migrations.DeleteModel(
            name='PaisZona',
        ),
        migrations.AddConstraint(
            model_name='paisprovincia',
            constraint=models.UniqueConstraint(fields=('id_pais', 'id_provincia'), name='uq_pais_provincia'),
        ),
    ]
